### PR TITLE
Updated readme.md

### LINKED ISSUE #34: updations in the readme file
Hey,
The contributing file has a scope of improvement and can be updated to a concise way after error removal.
I would like to contribute so please can you assign this issue to me.

### PR DESCRIPTION
**Pull request by shubhamshah14102**

### CODE REVIEW

**Comment by shubhamshah14102** [comment]
Couldnt figure out about the CLA Assistant .
Is anything expected from my end after creating the pull request to clear that pass?

**Comment by TwentyFourMinutes** [comment]
The commit seems good, thanks for the contribution. You need to acknowledge the CLA first. If you agree with it just post a single comment on this PR with the following content: `I have read the CLA Document and I hereby sign the CLA`.

**Comment by shubhamshah14102** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by TwentyFourMinutes** [comment]
You need to explicitly comment `I have read the CLA Document and I hereby sign the CLA` without the dot.

**Comment by shubhamshah14102** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by TwentyFourMinutes** [comment]
Thanks a lot for your contribution :)

**Review by TwentyFourMinutes — COMMENTED** [review]
👍

**Pull request merged**
