### PR TITLE
Fixed some general grammatical problems with README.md

### PR DESCRIPTION
**Pull request by AltriusRS**
Heya Twenti, i made some changes to README.md adding some commas where they should be, and changing the wording of things to make a little bit more sense.

Overall though, its looking pretty good!

### CODE REVIEW

**Comment by TwentyFourMinutes** [comment]
recheck

**Comment by TwentyFourMinutes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by TwentyFourMinutes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AltriusRS** [comment]
recheck

**Comment by AltriusRS** [comment]
recheck

**Comment by AltriusRS** [comment]
recheck

**Comment by AltriusRS** [comment]
recheck

**Comment by AltriusRS** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
